// src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			{/* <body> 태그에 Tailwind 클래스를 적용하여 테스트해볼 수 있습니다. */}
			<body className={`${inter.className} bg-slate-800 text-white`}>
				{children}
			</body>
		</html>
	);
}
